services:
  postgres:
    image: postgres:15
    container_name: human_detect_postgres
    environment:
      POSTGRES_DB: human_detect_db
      POSTGRES_USER: bict
      POSTGRES_PASSWORD: bict4486
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.4.0
  #   container_name: human_detect_zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "22181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:7.4.0
  #   container_name: human_detect_kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "30002:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: human_detect_zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:30002
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  postgres_data:
